# Sample .travis.yml for R projects

language: r
sudo: required

after_success:
  - Rscript -e "devtools::install_github('cpsievert/travistest')"
  - Rscript install.R

notifications:
  email:
    on_success: change
    on_failure: change
